from .contracts import MethodParameter, MethodSpec


SEGMENTATION_PLACEHOLDER_PARAMETERS = [
    MethodParameter(
        name="integration_mode",
        label="Integration Mode",
        type="select",
        default="placeholder",
        options=["placeholder", "local_import", "fastapi"],
        description="Use placeholder until your team connects a local Python callable or a FastAPI segmentation service.",
    ),
    MethodParameter(
        name="function_path",
        label="Local Function Path",
        type="string",
        default="",
        description="For local_import mode: dotted path to a callable, e.g. my_package.segmenters.run_yolo.",
    ),
    MethodParameter(
        name="fastapi_url",
        label="FastAPI URL",
        type="string",
        default="",
        description="For fastapi mode: URL that accepts SegmentInput-shaped JSON and returns SegmentOutput-shaped JSON.",
    ),
    MethodParameter(name="mode", label="Segmentation Mode", type="string", default="default"),
    MethodParameter(name="prompts", label="Prompts JSON", type="json", default={}),
    MethodParameter(name="options", label="Options JSON", type="json", default={}),
]


TOOLBOX_METHODS = [
    MethodSpec(
        id="source.project_part_images",
        name="Project Part Image Source",
        category="Input",
        description="Provides all images assigned to loaded inspection parts in the current VISTA project.",
        input_types=["any"],
        output_types=["image"],
        parameters=[
            MethodParameter(name="example_image_id", label="Choose Example", type="string", default=""),
        ],
        tags=["vista", "input", "parts"],
        jipipe_origin="Data source node",
    ),
    MethodSpec(
        id="output.versioned_image_artifact",
        name="Recipe / Artifact Output",
        category="Output",
        description="Stores processing versions as reproducible recipes, writes detections as metadata, persists spatial outputs as overlays, and materializes images only when needed.",
        input_types=["image", "mask", "labels", "detections", "measurements", "metadata"],
        output_types=["metadata"],
        parameters=[
            MethodParameter(
                name="mode",
                label="Output Mode",
                type="select",
                default="processing_sequence",
                options=["processing_sequence", "metadata_only", "overlay_artifact", "materialized_image", "review_only"],
            ),
            MethodParameter(
                name="export_policy",
                label="Export Policy",
                type="select",
                default="materialize_on_export",
                options=["materialize_on_export", "recipe_plus_artifacts", "metadata_only"],
            ),
            MethodParameter(name="materialize_processed_images", label="Materialize Processed Images", type="boolean", default=False),
        ],
        tags=["vista", "output", "recipe", "overlay", "metadata", "cache"],
        jipipe_origin="Data sink node",
    ),
    MethodSpec(
        id="preprocess.window_level_normalization",
        name="Window / Level Normalization",
        category="Preprocessing",
        description="Maps image intensities into a display or processing window using configurable level and width.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="window", label="Window", type="float", default=400.0, min_value=1.0),
            MethodParameter(name="level", label="Level", type="float", default=40.0),
            MethodParameter(name="clip", label="Clip Outliers", type="boolean", default=True),
        ],
        tags=["normalization", "intensity", "window-level"],
        jipipe_origin="ImageJ contrast/intensity adjustment",
    ),
    MethodSpec(
        id="preprocess.minmax_normalization",
        name="Min-Max Normalization",
        category="Preprocessing",
        description="Rescales image intensities to a target numeric range.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="output_min", label="Output Min", type="float", default=0.0),
            MethodParameter(name="output_max", label="Output Max", type="float", default=1.0),
        ],
        tags=["normalization", "intensity"],
        jipipe_origin="ImageJ normalize operation",
    ),
    MethodSpec(
        id="measure.region_properties",
        name="Region Properties (placeholder)",
        category="Measurement",
        description="Placeholder measurement block for area, centroid, bounding box, and intensity summaries. Replace with your deployed measurement implementation as needed.",
        input_types=["labels", "mask"],
        output_types=["measurements", "table"],
        parameters=[
            MethodParameter(
                name="features",
                label="Features",
                type="string",
                default="area,centroid,bbox,mean_intensity",
            ),
        ],
        tags=["measurement", "table", "placeholder"],
        jipipe_origin="Measure objects placeholder",
    ),
    MethodSpec(
        id="segmentation.yolo.placeholder",
        name="YOLO (placeholder)",
        category="Segmentation",
        description="Placeholder SegmentComponent backend for a YOLO segmentation implementation. Connect this block to a local Python callable or FastAPI service before deployed use.",
        output_types=["mask", "detections", "measurements"],
        parameters=SEGMENTATION_PLACEHOLDER_PARAMETERS,
        tags=["segmentation", "yolo", "placeholder", "custom-integration"],
        jipipe_origin="User-supplied segmentation implementation",
    ),
    MethodSpec(
        id="segmentation.anomalib.placeholder",
        name="Anomalib (placeholder)",
        category="Segmentation",
        description="Placeholder SegmentComponent backend for an Anomalib anomaly-mask implementation. Connect this block to a local Python callable or FastAPI service before deployed use.",
        output_types=["mask", "measurements", "metadata"],
        parameters=SEGMENTATION_PLACEHOLDER_PARAMETERS,
        tags=["segmentation", "anomalib", "anomaly", "placeholder", "custom-integration"],
        jipipe_origin="User-supplied segmentation implementation",
    ),
    MethodSpec(
        id="segmentation.sam.placeholder",
        name="SAM (placeholder)",
        category="Segmentation",
        description="Placeholder SegmentComponent backend for a Segment Anything implementation. Connect this block to a local Python callable or FastAPI service before deployed use.",
        output_types=["mask", "measurements"],
        parameters=SEGMENTATION_PLACEHOLDER_PARAMETERS,
        tags=["segmentation", "sam", "promptable", "placeholder", "custom-integration"],
        jipipe_origin="User-supplied segmentation implementation",
    ),
    MethodSpec(
        id="segmentation.opencv.placeholder",
        name="OpenCV (placeholder)",
        category="Segmentation",
        description="Placeholder SegmentComponent backend for a classical OpenCV segmentation implementation. Connect this block to a local Python callable or FastAPI service before deployed use.",
        output_types=["mask", "measurements"],
        parameters=SEGMENTATION_PLACEHOLDER_PARAMETERS,
        tags=["segmentation", "opencv", "placeholder", "custom-integration"],
        jipipe_origin="User-supplied segmentation implementation",
    ),
]
